### ISSUE TITLE
Bracket notation doesn't overwrite defaults

### ISSUE THREAD

**Issue by manurg** [jenius/rupture#56]
I came across a weird behavior while using Rupture.

When defining settings in bracket notation, e.g.
``` javascript
rupture['scale']          =  0       250px     460px     768px     1024px      1280px       1600px     1920px
                          // ├─────────┼─────────┼─────────┼─────────┼───────────┼────────────┼─────────>
rupture['scale-names']    =  'xs'     's'       'sm'      'm'       'l'        'xl'          'xxl'
```

the default values won't be overwritten.
When using it like

``` css
.foo
  +above('l')
    display block
```

it compiles to

``` css
@media only screen and (min-width: 800px) {
  .foo {
    display: block;
  }

@media only screen and (min-width: 1025px) {
  .foo {
    display: block;
  }
```

Using dot notation (like you do in the description) solves this issue.
Just wanted to let you know i came across this "bug".
